app/__init__.py
# -*- coding: utf-8 -*-

import os
import time
from threading import Thread
import schedule
from werkzeug.contrib.fixers import ProxyFix
from app.constants import *
from flask import *
from app.league import run_competition


def scheduling():
    while True:
        schedule.run_pending()
        time.sleep(1)


def check_directories():
    if not os.path.isdir(BOTS_FOLDER):
        os.mkdir(BOTS_FOLDER)
    if not os.path.isdir(DATA_FOLDER):
        os.mkdir(DATA_FOLDER)


def start_scheduling():
    for x in range(EXECUTIONS_PER_DAY):
        h = int(x * 24 / EXECUTIONS_PER_DAY)
        t = '{}:00'.format(str(h).zfill(2))
        schedule.every().day.at(t).do(run_competition)
    Thread(target=scheduling).start()


def create_app():
    app = Flask(__name__)
    app.config.from_object('config')
    app.wsgi_app = ProxyFix(app.wsgi_app)
    app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER
    app.config['ALLOWED_EXTENSIONS'] = set(['h', 'hpp', 'cpp'])
    app.jinja_env.trim_blocks = True
    return app

app/views.py
# -*- coding: utf-8 -*-

import os
import logging
from app import league, utilities
from app.constants import BOTS_FOLDER, UPLOAD_FOLDER
from werkzeug import secure_filename
from flask import render_template, request, Blueprint
from app.utilities import render_dataframe


bp = Blueprint('bp', __name__)


def alert_page(title, content):
    return render_template('page.html', title=title, content=content)


@bp.route('/subirbot')
def subirbot():
    if league.is_running_competition:
        return alert_page('Error',
                          'Se está ejecutando una competicion, no se pueden subir bots.')
    else:
        return render_template('upload.html')


@bp.route("/")
def index():
    try:
        (exec_date, ranking) = league.get_current_data(True, False, True)
        next_exec = league.get_next_execution()
        ranking_render = render_dataframe(df=ranking, html_id='ranking')
        return render_template('liga.html', tables=[ranking_render],
                               titles=['na', 'Ranking'],
                               exec_date=exec_date, next_exec=next_exec,
                               is_running=league.is_running_competition,
                               bot_list=league.get_bot_list())
    except FileNotFoundError as ex:
        logging.error(ex)
        return alert_page('No hay datos',
                          'No existen datos actuales de la liga.')


@bp.route("/ejecutar1234")
def ejecutar():
    if league.run_competition(block_thread=False):
        return alert_page('Ejecutando competicion',
                          'Ejecutando competición... en unos minutos se actualizarán los resultados')
    else:
        return alert_page('Competicion en curso',
                          'Competición en curso, espera a que termine para ejecutar otra.')


@bp.route('/lista')
def lista():
    return render_template('lista.html', bot_list=league.get_bot_list())


@bp.route('/upload', methods=['POST'])
def upload():
    uploaded_files = request.files.getlist("file[]")
    cond1 = len(uploaded_files) == 2
    cond2 = all(utilities.allowed_file(x.filename) for x in uploaded_files)
    cond3 = all(not os.path.exists(os.path.join(UPLOAD_FOLDER, x.filename))
                for x in uploaded_files)
    if not (cond1 and cond2 and cond3):
        return alert_page('Error',
                          'Sube únicamente los archivos .h y .cpp de tu bot')
    filenames = []
    for file in uploaded_files:
        filename = secure_filename(file.filename)
        file.save(os.path.join(UPLOAD_FOLDER, filename))
        filenames.append(filename)
    if not utilities.legal_files(filenames):
        return alert_page('Error',
                          'Se han detectado llamadas al sistema ilegales')
    elif utilities.compile_bot(filenames):
        return alert_page('Completado', 'Bot compilado con exito.')
    else:
        return alert_page('Error', 'No se puede compilar el bot')


@bp.route('/ejecutar_partido/', methods=['POST'])
def ejecutar_partido():
    bot1 = request.form.get('bot1_select')
    bot2 = request.form.get('bot2_select')
    m1 = league.run_match(bot1, bot2)
    matches = [m1]
    if request.form.getlist('ida_y_vuelta'):
        m2 = league.run_match(bot2, bot1)
        matches.append(m2)
    table = render_dataframe(league.create_matches_table(matches), 'ranking')
    return render_template('resultados.html', table=table)


@bp.route('/mostrar_resultados/', methods=['POST'])
def mostrar_resultados():
    bot  = request.form.get('bot_select')
    data = league.get_bot_matches_data(bot)
    table = render_dataframe(df=data, html_id='matches')
    return render_template('resultados.html', table=table)


@bp.route('/partido/')
def partido():
    if league.is_running_competition:
        return alert_page('Error',
                          'Se está ejecutando una competicion, no se pueden realizar partidos individuales.')
    else:
        return render_template('partido.html', bot_list=league.get_bot_list())

app/templates/liga.html
<!doctype html>
<html lang="en">
  <head>
    <title>Liga Underground Mancala</title>
    <link rel=stylesheet type=text/css href="{{ url_for('static', filename='mancala.css') }}">
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.10.16/datatables.min.css"/>
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.16/datatables.min.js"></script>
    <script>
      $(document).ready(function() { $('#ranking').DataTable(); });
    </script>
  </head>
  <body>
    <nav class="navbar navbar-default">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/">Resultados</a></li>
        <li><a href="/subirbot">Subir bot</a></li>
        <li><a href="/lista">Listado</a></li>
        <li><a href="/partido">Partido</a></li>
      </ul>
    </nav>
    <div style="float:left; width:75%; padding-left:1em;">
      <h1 class="league-title">Liga Underground de Mancala</h1>
      <h3>Última ejecución: {{ exec_date }}</h3>
      {% if not is_running %}
      <h3 id ="time-left"></h3>
      <script type="text/javascript" src="{{ url_for('static', filename='js/countdown.js') }}"></script>
      <script type="text/javascript">
        countdown("time-left", "{{ next_exec }}");
      </script>
      {% else %}
      <h3>En ejecución...</h3>
      {% endif %}

      {% for table in tables %}
      <h2>{{titles[loop.index]}}</h2>
      {{ table|safe }}
      {% endfor %}

      <h2>Partidos</h2>
      <form method='POST' action="{{ url_for('bp.mostrar_resultados') }}">
        <div class="form-inline">
          <label for="bot1_select">Jugador 1:</label>
          <select name="bot_select" class="selectpicker form-control">
            {% for bot in bot_list %}
            <option>{{bot}}</option>
            {% endfor %}
          </select>
          <button type="submit" class="btn btn-primary">Mostrar resultados</button>
        </div>
      </form>

      <div style="padding-top:1em; width:100%">
        <h1 class="league-title">Desarrollado por</h1>
        <div style="padding-top:1em;">
          <div style="float:left; width:50%;">
            <div class="github-card" data-github="AlvaroGarciaJaen" data-width="450" data-height="" data-theme="default"></div>
          </div>
          <div style="float:right; width:50%; padding-left:0em;">
            <div class="github-card" data-github="antoniomdk" data-width="450" data-height="" data-theme="default"></div>
          </div>
          <h1>Apóyanos</h1>
          <div class="github-card" data-user="AlvaroGarciaJaen" data-repo="mancala-league"></div>
        </div>
        <script src="//cdn.jsdelivr.net/github-cards/latest/widget.js"></script>
      </div>
  </body>
</html>

app/templates/lista.html
<!doctype html>
<html lang="en">
  <head>
    <link rel=stylesheet type=text/css href="{{ url_for('static', filename='mancala.css') }}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <title>Listado de bots</title>
  </head>
  <body>
    <nav class="navbar navbar-default">
      <ul class="nav navbar-nav">
        <li><a href="/">Resultados</a></li>
        <li><a href="/subirbot">Subir bot</a></li>
        <li class="active"><a href="/lista">Listado</a></li>
        <li><a href="/partido">Partido</a></li>
      </ul>
    </nav>
    <div style="padding-left:1em">
      <h1>Listado de bots</h1>
      <ul>
        {% for bot in bot_list %}
        <li>{{bot}}</li>
        {% endfor %}
      </ul>
    </div>
  </body>
</html>

app/templates/page.html
<!doctype html>
<html lang="en">
  <head>
      <title>{{title}}</title>
    <link rel=stylesheet type=text/css href="{{ url_for('static', filename='mancala.css') }}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  </head>
  <body>
    <nav class="navbar navbar-default">
      <ul class="nav navbar-nav">
        <li><a href="/">Resultados</a></li>
        <li><a href="/subirbot">Subir bot</a></li>
        <li><a href="/lista">Listado</a></li>
        <li><a href="/partido">Partido</a></li>
      </ul>
    </nav>
    <div style="padding-left:1em;">{{content}}</div>
  </body>
</html>

app/templates/partido.html
<!doctype html>
<html lang="en">
  <head>
    <title>Partido</title>
    <link rel=stylesheet type=text/css href="{{ url_for('static', filename='mancala.css') }}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  </head>
  <body>
    <nav class="navbar navbar-default">
      <ul class="nav navbar-nav">
        <li><a href="/">Resultados</a></li>
        <li><a href="/subirbot">Subir bot</a></li>
        <li><a href="/lista">Listado</a></li>
        <li class="active"><a href="/partido">Partido</a></li>
      </ul>
    </nav>
    <div style="float:left; width:50%; padding-left:2em;">
      <form method='POST' action="{{ url_for('bp.ejecutar_partido') }}">
        <div class="form-group">
          <label for="bot1_select">Jugador 1:</label>
          <select name="bot1_select" class="selectpicker form-control">
            {% for bot in bot_list %}
            <option>{{bot}}</option>
            {% endfor %}
          </select>
        </div>
        <div class="form-group">
          <label for="bot2_select">Jugador 2:</label>
          <select name="bot2_select" class="selectpicker form-control">
            {% for bot in bot_list %}
            <option>{{bot}}</option>
            {% endfor %}
          </select>
        </div>
        <div class="form-check">
          <input class="form-check-input" type="checkbox" value="1" name="ida_y_vuelta">
          <label class="form-check-label" for="ida_y_vuelta"> Ida y vuelta </label>
        </div>
        <button type="submit" class="btn btn-primary">Ejecutar partido</button>
      </form>
    </div>
  </body>
</html>

app/templates/resultados.html
<!doctype html>
<html lang="en">
  <head>
    <title>Liga Underground Mancala</title>
    <link rel=stylesheet type=text/css href="{{ url_for('static', filename='mancala.css') }}">
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.10.16/datatables.min.css"/>
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.16/datatables.min.js"></script>
    <script>
      $(document).ready(function() { $('#matches').DataTable(); });
    </script>
  </head>
  <body>
    <nav class="navbar navbar-default">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/">Resultados</a></li>
        <li><a href="/subirbot">Subir bot</a></li>
        <li><a href="/lista">Listado</a></li>
        <li><a href="/partido">Partido</a></li>
      </ul>
    </nav>
    <div style="float:left; width:75%; padding-left:1em;">
        <h2>Partidos</h2>
        {{table | safe}}
    </div>
  </body>
</html>

app/templates/upload.html
<!DOCTYPE html>
<html lang="en">
  <title>Subir bot</title>
  <link rel=stylesheet type=text/css href="{{ url_for('static', filename='mancala.css') }}">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <body>
    <nav class="navbar navbar-default">
      <ul class="nav navbar-nav">
        <li><a href="/">Resultados</a></li>
        <li class="active"><a href="/subirbot">Subir bot</a></li>
        <li><a href="/lista">Listado</a></li>
        <li><a href="/partido">Partido</a></li>
      </ul>
    </nav>
    <div style="padding-left:1em;">
      <h4>Sube los archivos de cabecera e implementación de tu bot.</h4>
      <form action="upload" method="post" enctype="multipart/form-data">
        <input type="file" multiple="" name="file[]" class="span3" /><br />
        <input type="submit" value="Subir"  class="span2">
      </form>
    </div>
  </body>
</html>